#
#Tue Dec 02 17:21:36 CST 2025
android.enableJetifier=true
android.injected.testOnly=false
android.useAndroidX=true
isNotNeedLogin=true
mavenCentralPassword=XUrCbYixJ7i3ObbsSF5yY81wx4zc4gl0mOoVGrMEYkoM
mavenCentralUsername=InXbHiE9
mavenSnapshot=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
readyPublishGithub=true
readyPublishMaven=true
signing.keyId=1E33CCA1
signing.password=jingwu_345
signing.secretKeyRingFile=/Users/hefeng02/.gradle/secret.gpg
