// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/users.proto

package io.agora.report.v2.protobuf;

/**
 * <pre>
 * id = 9012
 * </pre>
 *
 * Protobuf type {@code google.protobuf.ApaasUserJoin}
 */
public  final class ApaasUserJoin extends
    com.google.protobuf.GeneratedMessageLite<
        ApaasUserJoin, ApaasUserJoin.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.ApaasUserJoin)
    ApaasUserJoinOrBuilder {
  private ApaasUserJoin() {
    ver_ = "";
    scenario_ = "";
    uid_ = "";
    userName_ = "";
    streamSuid_ = "";
    role_ = "";
    streamSid_ = "";
    rtmSid_ = "";
    roomId_ = "";
  }
  public static final int LTS_FIELD_NUMBER = 1;
  private long lts_;
  /**
   * <pre>
   * 时间戳，必须存在
   * </pre>
   *
   * <code>int64 lts = 1;</code>
   * @return The lts.
   */
  @Override
  public long getLts() {
    return lts_;
  }
  /**
   * <pre>
   * 时间戳，必须存在
   * </pre>
   *
   * <code>int64 lts = 1;</code>
   * @param value The lts to set.
   */
  private void setLts(long value) {
    
    lts_ = value;
  }
  /**
   * <pre>
   * 时间戳，必须存在
   * </pre>
   *
   * <code>int64 lts = 1;</code>
   */
  private void clearLts() {
    
    lts_ = 0L;
  }

  public static final int VID_FIELD_NUMBER = 2;
  private int vid_;
  /**
   * <pre>
   * vid
   * </pre>
   *
   * <code>int32 vid = 2;</code>
   * @return The vid.
   */
  @Override
  public int getVid() {
    return vid_;
  }
  /**
   * <pre>
   * vid
   * </pre>
   *
   * <code>int32 vid = 2;</code>
   * @param value The vid to set.
   */
  private void setVid(int value) {
    
    vid_ = value;
  }
  /**
   * <pre>
   * vid
   * </pre>
   *
   * <code>int32 vid = 2;</code>
   */
  private void clearVid() {
    
    vid_ = 0;
  }

  public static final int VER_FIELD_NUMBER = 3;
  private String ver_;
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @return The ver.
   */
  @Override
  public String getVer() {
    return ver_;
  }
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @return The bytes for ver.
   */
  @Override
  public com.google.protobuf.ByteString
      getVerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ver_);
  }
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @param value The ver to set.
   */
  private void setVer(
      String value) {
    Class<?> valueClass = value.getClass();
  
    ver_ = value;
  }
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   */
  private void clearVer() {
    
    ver_ = getDefaultInstance().getVer();
  }
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @param value The bytes for ver to set.
   */
  private void setVerBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ver_ = value.toStringUtf8();
    
  }

  public static final int SCENARIO_FIELD_NUMBER = 4;
  private String scenario_;
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @return The scenario.
   */
  @Override
  public String getScenario() {
    return scenario_;
  }
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @return The bytes for scenario.
   */
  @Override
  public com.google.protobuf.ByteString
      getScenarioBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(scenario_);
  }
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @param value The scenario to set.
   */
  private void setScenario(
      String value) {
    Class<?> valueClass = value.getClass();
  
    scenario_ = value;
  }
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   */
  private void clearScenario() {
    
    scenario_ = getDefaultInstance().getScenario();
  }
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @param value The bytes for scenario to set.
   */
  private void setScenarioBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    scenario_ = value.toStringUtf8();
    
  }

  public static final int ERRORCODE_FIELD_NUMBER = 5;
  private int errorCode_;
  /**
   * <pre>
   * 异常码，若有
   * </pre>
   *
   * <code>int32 errorCode = 5;</code>
   * @return The errorCode.
   */
  @Override
  public int getErrorCode() {
    return errorCode_;
  }
  /**
   * <pre>
   * 异常码，若有
   * </pre>
   *
   * <code>int32 errorCode = 5;</code>
   * @param value The errorCode to set.
   */
  private void setErrorCode(int value) {
    
    errorCode_ = value;
  }
  /**
   * <pre>
   * 异常码，若有
   * </pre>
   *
   * <code>int32 errorCode = 5;</code>
   */
  private void clearErrorCode() {
    
    errorCode_ = 0;
  }

  public static final int UID_FIELD_NUMBER = 6;
  private String uid_;
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @return The uid.
   */
  @Override
  public String getUid() {
    return uid_;
  }
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @return The bytes for uid.
   */
  @Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uid_);
  }
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @param value The uid to set.
   */
  private void setUid(
      String value) {
    Class<?> valueClass = value.getClass();
  
    uid_ = value;
  }
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   */
  private void clearUid() {
    
    uid_ = getDefaultInstance().getUid();
  }
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @param value The bytes for uid to set.
   */
  private void setUidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uid_ = value.toStringUtf8();
    
  }

  public static final int USERNAME_FIELD_NUMBER = 7;
  private String userName_;
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @return The userName.
   */
  @Override
  public String getUserName() {
    return userName_;
  }
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @return The bytes for userName.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userName_);
  }
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @param value The userName to set.
   */
  private void setUserName(
      String value) {
    Class<?> valueClass = value.getClass();
  
    userName_ = value;
  }
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   */
  private void clearUserName() {
    
    userName_ = getDefaultInstance().getUserName();
  }
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @param value The bytes for userName to set.
   */
  private void setUserNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userName_ = value.toStringUtf8();
    
  }

  public static final int STREAMUID_FIELD_NUMBER = 8;
  private long streamUid_;
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>int64 streamUid = 8;</code>
   * @return The streamUid.
   */
  @Override
  public long getStreamUid() {
    return streamUid_;
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>int64 streamUid = 8;</code>
   * @param value The streamUid to set.
   */
  private void setStreamUid(long value) {
    
    streamUid_ = value;
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>int64 streamUid = 8;</code>
   */
  private void clearStreamUid() {
    
    streamUid_ = 0L;
  }

  public static final int STREAMSUID_FIELD_NUMBER = 9;
  private String streamSuid_;
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @return The streamSuid.
   */
  @Override
  public String getStreamSuid() {
    return streamSuid_;
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @return The bytes for streamSuid.
   */
  @Override
  public com.google.protobuf.ByteString
      getStreamSuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(streamSuid_);
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @param value The streamSuid to set.
   */
  private void setStreamSuid(
      String value) {
    Class<?> valueClass = value.getClass();
  
    streamSuid_ = value;
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   */
  private void clearStreamSuid() {
    
    streamSuid_ = getDefaultInstance().getStreamSuid();
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @param value The bytes for streamSuid to set.
   */
  private void setStreamSuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    streamSuid_ = value.toStringUtf8();
    
  }

  public static final int ROLE_FIELD_NUMBER = 10;
  private String role_;
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The role.
   */
  @Override
  public String getRole() {
    return role_;
  }
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The bytes for role.
   */
  @Override
  public com.google.protobuf.ByteString
      getRoleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(role_);
  }
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @param value The role to set.
   */
  private void setRole(
      String value) {
    Class<?> valueClass = value.getClass();
  
    role_ = value;
  }
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   */
  private void clearRole() {
    
    role_ = getDefaultInstance().getRole();
  }
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @param value The bytes for role to set.
   */
  private void setRoleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    role_ = value.toStringUtf8();
    
  }

  public static final int STREAMSID_FIELD_NUMBER = 11;
  private String streamSid_;
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @return The streamSid.
   */
  @Override
  public String getStreamSid() {
    return streamSid_;
  }
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @return The bytes for streamSid.
   */
  @Override
  public com.google.protobuf.ByteString
      getStreamSidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(streamSid_);
  }
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @param value The streamSid to set.
   */
  private void setStreamSid(
      String value) {
    Class<?> valueClass = value.getClass();
  
    streamSid_ = value;
  }
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   */
  private void clearStreamSid() {
    
    streamSid_ = getDefaultInstance().getStreamSid();
  }
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @param value The bytes for streamSid to set.
   */
  private void setStreamSidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    streamSid_ = value.toStringUtf8();
    
  }

  public static final int RTMSID_FIELD_NUMBER = 12;
  private String rtmSid_;
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @return The rtmSid.
   */
  @Override
  public String getRtmSid() {
    return rtmSid_;
  }
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @return The bytes for rtmSid.
   */
  @Override
  public com.google.protobuf.ByteString
      getRtmSidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(rtmSid_);
  }
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @param value The rtmSid to set.
   */
  private void setRtmSid(
      String value) {
    Class<?> valueClass = value.getClass();
  
    rtmSid_ = value;
  }
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   */
  private void clearRtmSid() {
    
    rtmSid_ = getDefaultInstance().getRtmSid();
  }
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @param value The bytes for rtmSid to set.
   */
  private void setRtmSidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    rtmSid_ = value.toStringUtf8();
    
  }

  public static final int ROOMID_FIELD_NUMBER = 13;
  private String roomId_;
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @return The roomId.
   */
  @Override
  public String getRoomId() {
    return roomId_;
  }
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @return The bytes for roomId.
   */
  @Override
  public com.google.protobuf.ByteString
      getRoomIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roomId_);
  }
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @param value The roomId to set.
   */
  private void setRoomId(
      String value) {
    Class<?> valueClass = value.getClass();
  
    roomId_ = value;
  }
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   */
  private void clearRoomId() {
    
    roomId_ = getDefaultInstance().getRoomId();
  }
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @param value The bytes for roomId to set.
   */
  private void setRoomIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    roomId_ = value.toStringUtf8();
    
  }

  public static ApaasUserJoin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ApaasUserJoin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ApaasUserJoin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ApaasUserJoin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ApaasUserJoin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ApaasUserJoin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ApaasUserJoin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ApaasUserJoin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(ApaasUserJoin prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * id = 9012
   * </pre>
   *
   * Protobuf type {@code google.protobuf.ApaasUserJoin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ApaasUserJoin, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.ApaasUserJoin)
      ApaasUserJoinOrBuilder {
    // Construct using io.agora.report.v2.protobuf.ApaasUserJoin.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @return The lts.
     */
    @Override
    public long getLts() {
      return instance.getLts();
    }
    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @param value The lts to set.
     * @return This builder for chaining.
     */
    public Builder setLts(long value) {
      copyOnWrite();
      instance.setLts(value);
      return this;
    }
    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLts() {
      copyOnWrite();
      instance.clearLts();
      return this;
    }

    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @return The vid.
     */
    @Override
    public int getVid() {
      return instance.getVid();
    }
    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @param value The vid to set.
     * @return This builder for chaining.
     */
    public Builder setVid(int value) {
      copyOnWrite();
      instance.setVid(value);
      return this;
    }
    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVid() {
      copyOnWrite();
      instance.clearVid();
      return this;
    }

    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return The ver.
     */
    @Override
    public String getVer() {
      return instance.getVer();
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return The bytes for ver.
     */
    @Override
    public com.google.protobuf.ByteString
        getVerBytes() {
      return instance.getVerBytes();
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @param value The ver to set.
     * @return This builder for chaining.
     */
    public Builder setVer(
        String value) {
      copyOnWrite();
      instance.setVer(value);
      return this;
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVer() {
      copyOnWrite();
      instance.clearVer();
      return this;
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @param value The bytes for ver to set.
     * @return This builder for chaining.
     */
    public Builder setVerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVerBytes(value);
      return this;
    }

    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return The scenario.
     */
    @Override
    public String getScenario() {
      return instance.getScenario();
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return The bytes for scenario.
     */
    @Override
    public com.google.protobuf.ByteString
        getScenarioBytes() {
      return instance.getScenarioBytes();
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @param value The scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenario(
        String value) {
      copyOnWrite();
      instance.setScenario(value);
      return this;
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScenario() {
      copyOnWrite();
      instance.clearScenario();
      return this;
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @param value The bytes for scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenarioBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setScenarioBytes(value);
      return this;
    }

    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @return The errorCode.
     */
    @Override
    public int getErrorCode() {
      return instance.getErrorCode();
    }
    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {
      copyOnWrite();
      instance.setErrorCode(value);
      return this;
    }
    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      copyOnWrite();
      instance.clearErrorCode();
      return this;
    }

    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return The uid.
     */
    @Override
    public String getUid() {
      return instance.getUid();
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return The bytes for uid.
     */
    @Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      return instance.getUidBytes();
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        String value) {
      copyOnWrite();
      instance.setUid(value);
      return this;
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      copyOnWrite();
      instance.clearUid();
      return this;
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUidBytes(value);
      return this;
    }

    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      return instance.getUserName();
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return instance.getUserNameBytes();
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        String value) {
      copyOnWrite();
      instance.setUserName(value);
      return this;
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      copyOnWrite();
      instance.clearUserName();
      return this;
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @return The streamUid.
     */
    @Override
    public long getStreamUid() {
      return instance.getStreamUid();
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @param value The streamUid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamUid(long value) {
      copyOnWrite();
      instance.setStreamUid(value);
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamUid() {
      copyOnWrite();
      instance.clearStreamUid();
      return this;
    }

    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return The streamSuid.
     */
    @Override
    public String getStreamSuid() {
      return instance.getStreamSuid();
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return The bytes for streamSuid.
     */
    @Override
    public com.google.protobuf.ByteString
        getStreamSuidBytes() {
      return instance.getStreamSuidBytes();
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @param value The streamSuid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSuid(
        String value) {
      copyOnWrite();
      instance.setStreamSuid(value);
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamSuid() {
      copyOnWrite();
      instance.clearStreamSuid();
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @param value The bytes for streamSuid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStreamSuidBytes(value);
      return this;
    }

    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return The role.
     */
    @Override
    public String getRole() {
      return instance.getRole();
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return The bytes for role.
     */
    @Override
    public com.google.protobuf.ByteString
        getRoleBytes() {
      return instance.getRoleBytes();
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
        String value) {
      copyOnWrite();
      instance.setRole(value);
      return this;
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      copyOnWrite();
      instance.clearRole();
      return this;
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRoleBytes(value);
      return this;
    }

    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return The streamSid.
     */
    @Override
    public String getStreamSid() {
      return instance.getStreamSid();
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return The bytes for streamSid.
     */
    @Override
    public com.google.protobuf.ByteString
        getStreamSidBytes() {
      return instance.getStreamSidBytes();
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @param value The streamSid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSid(
        String value) {
      copyOnWrite();
      instance.setStreamSid(value);
      return this;
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamSid() {
      copyOnWrite();
      instance.clearStreamSid();
      return this;
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @param value The bytes for streamSid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStreamSidBytes(value);
      return this;
    }

    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return The rtmSid.
     */
    @Override
    public String getRtmSid() {
      return instance.getRtmSid();
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return The bytes for rtmSid.
     */
    @Override
    public com.google.protobuf.ByteString
        getRtmSidBytes() {
      return instance.getRtmSidBytes();
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @param value The rtmSid to set.
     * @return This builder for chaining.
     */
    public Builder setRtmSid(
        String value) {
      copyOnWrite();
      instance.setRtmSid(value);
      return this;
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRtmSid() {
      copyOnWrite();
      instance.clearRtmSid();
      return this;
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @param value The bytes for rtmSid to set.
     * @return This builder for chaining.
     */
    public Builder setRtmSidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRtmSidBytes(value);
      return this;
    }

    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return The roomId.
     */
    @Override
    public String getRoomId() {
      return instance.getRoomId();
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return The bytes for roomId.
     */
    @Override
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      return instance.getRoomIdBytes();
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(
        String value) {
      copyOnWrite();
      instance.setRoomId(value);
      return this;
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      copyOnWrite();
      instance.clearRoomId();
      return this;
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @param value The bytes for roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRoomIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.ApaasUserJoin)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ApaasUserJoin();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "lts_",
            "vid_",
            "ver_",
            "scenario_",
            "errorCode_",
            "uid_",
            "userName_",
            "streamUid_",
            "streamSuid_",
            "role_",
            "streamSid_",
            "rtmSid_",
            "roomId_",
          };
          String info =
              "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0000\u0000\u0001\u0002\u0002\u0004\u0003\u0208" +
              "\u0004\u0208\u0005\u0004\u0006\u0208\u0007\u0208\b\u0002\t\u0208\n\u0208\u000b\u0208" +
              "\f\u0208\r\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<ApaasUserJoin> parser = PARSER;
        if (parser == null) {
          synchronized (ApaasUserJoin.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<ApaasUserJoin>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.ApaasUserJoin)
  private static final ApaasUserJoin DEFAULT_INSTANCE;
  static {
    ApaasUserJoin defaultInstance = new ApaasUserJoin();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ApaasUserJoin.class, defaultInstance);
  }

  public static ApaasUserJoin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ApaasUserJoin> PARSER;

  public static com.google.protobuf.Parser<ApaasUserJoin> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

