// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/users.proto

package io.agora.report.v2.protobuf;

public final class APaasReportV2 {
  private APaasReportV2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
