// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/users.proto

package io.agora.edu.core.internal.report.v2.protobuf;

/**
 * <pre>
 * id = 9012
 * </pre>
 *
 * Protobuf type {@code google.protobuf.ApaasUserJoin}
 */
public final class ApaasUserJoin extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:google.protobuf.ApaasUserJoin)
        ApaasUserJoinOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use ApaasUserJoin.newBuilder() to construct.
  private ApaasUserJoin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ApaasUserJoin() {
    ver_ = "";
    scenario_ = "";
    uid_ = "";
    userName_ = "";
    streamSuid_ = "";
    role_ = "";
    streamSid_ = "";
    rtmSid_ = "";
    roomId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
          UnusedPrivateParameter unused) {
    return new ApaasUserJoin();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ApaasUserJoin(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            lts_ = input.readInt64();
            break;
          }
          case 16: {

            vid_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            ver_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            scenario_ = s;
            break;
          }
          case 40: {

            errorCode_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            uid_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 64: {

            streamUid_ = input.readInt64();
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            streamSuid_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            role_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            streamSid_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            rtmSid_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            roomId_ = s;
            break;
          }
          case 112: {

            roomCreateTs_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return APaasReportV2.internal_static_google_protobuf_ApaasUserJoin_descriptor;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return APaasReportV2.internal_static_google_protobuf_ApaasUserJoin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    ApaasUserJoin.class, Builder.class);
  }

  public static final int LTS_FIELD_NUMBER = 1;
  private long lts_;
  /**
   * <pre>
   * 时间戳，必须存在
   * </pre>
   *
   * <code>int64 lts = 1;</code>
   * @return The lts.
   */
  @Override
  public long getLts() {
    return lts_;
  }

  public static final int VID_FIELD_NUMBER = 2;
  private int vid_;
  /**
   * <pre>
   * vid
   * </pre>
   *
   * <code>int32 vid = 2;</code>
   * @return The vid.
   */
  @Override
  public int getVid() {
    return vid_;
  }

  public static final int VER_FIELD_NUMBER = 3;
  private volatile Object ver_;
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @return The ver.
   */
  @Override
  public String getVer() {
    Object ref = ver_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ver_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * apaas版本号
   * </pre>
   *
   * <code>string ver = 3;</code>
   * @return The bytes for ver.
   */
  @Override
  public com.google.protobuf.ByteString
  getVerBytes() {
    Object ref = ver_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      ver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCENARIO_FIELD_NUMBER = 4;
  private volatile Object scenario_;
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @return The scenario.
   */
  @Override
  public String getScenario() {
    Object ref = scenario_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      scenario_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * apaas场景，如education/meeting/entertainment
   * </pre>
   *
   * <code>string scenario = 4;</code>
   * @return The bytes for scenario.
   */
  @Override
  public com.google.protobuf.ByteString
  getScenarioBytes() {
    Object ref = scenario_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      scenario_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORCODE_FIELD_NUMBER = 5;
  private int errorCode_;
  /**
   * <pre>
   * 异常码，若有
   * </pre>
   *
   * <code>int32 errorCode = 5;</code>
   * @return The errorCode.
   */
  @Override
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int UID_FIELD_NUMBER = 6;
  private volatile Object uid_;
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @return The uid.
   */
  @Override
  public String getUid() {
    Object ref = uid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * apaas用户id，同RTM uid
   * </pre>
   *
   * <code>string uid = 6;</code>
   * @return The bytes for uid.
   */
  @Override
  public com.google.protobuf.ByteString
  getUidBytes() {
    Object ref = uid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 7;
  private volatile Object userName_;
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @return The userName.
   */
  @Override
  public String getUserName() {
    Object ref = userName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户名，用于显示
   * </pre>
   *
   * <code>string userName = 7;</code>
   * @return The bytes for userName.
   */
  @Override
  public com.google.protobuf.ByteString
  getUserNameBytes() {
    Object ref = userName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREAMUID_FIELD_NUMBER = 8;
  private long streamUid_;
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>int64 streamUid = 8;</code>
   * @return The streamUid.
   */
  @Override
  public long getStreamUid() {
    return streamUid_;
  }

  public static final int STREAMSUID_FIELD_NUMBER = 9;
  private volatile Object streamSuid_;
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @return The streamSuid.
   */
  @Override
  public String getStreamSuid() {
    Object ref = streamSuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      streamSuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * rtc流id
   * </pre>
   *
   * <code>string streamSuid = 9;</code>
   * @return The bytes for streamSuid.
   */
  @Override
  public com.google.protobuf.ByteString
  getStreamSuidBytes() {
    Object ref = streamSuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      streamSuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 10;
  private volatile Object role_;
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The role.
   */
  @Override
  public String getRole() {
    Object ref = role_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      role_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * apaas角色
   * </pre>
   *
   * <code>string role = 10;</code>
   * @return The bytes for role.
   */
  @Override
  public com.google.protobuf.ByteString
  getRoleBytes() {
    Object ref = role_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      role_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREAMSID_FIELD_NUMBER = 11;
  private volatile Object streamSid_;
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @return The streamSid.
   */
  @Override
  public String getStreamSid() {
    Object ref = streamSid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      streamSid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * rtc sid
   * </pre>
   *
   * <code>string streamSid = 11;</code>
   * @return The bytes for streamSid.
   */
  @Override
  public com.google.protobuf.ByteString
  getStreamSidBytes() {
    Object ref = streamSid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      streamSid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RTMSID_FIELD_NUMBER = 12;
  private volatile Object rtmSid_;
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @return The rtmSid.
   */
  @Override
  public String getRtmSid() {
    Object ref = rtmSid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      rtmSid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * rtm sid
   * </pre>
   *
   * <code>string rtmSid = 12;</code>
   * @return The bytes for rtmSid.
   */
  @Override
  public com.google.protobuf.ByteString
  getRtmSidBytes() {
    Object ref = rtmSid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      rtmSid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMID_FIELD_NUMBER = 13;
  private volatile Object roomId_;
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @return The roomId.
   */
  @Override
  public String getRoomId() {
    Object ref = roomId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      roomId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * apaas房间id，与rtc/rtm channelName相同
   * </pre>
   *
   * <code>string roomId = 13;</code>
   * @return The bytes for roomId.
   */
  @Override
  public com.google.protobuf.ByteString
  getRoomIdBytes() {
    Object ref = roomId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      roomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMCREATETS_FIELD_NUMBER = 14;
  private long roomCreateTs_;
  /**
   * <pre>
   * room create timestamp
   * </pre>
   *
   * <code>int64 roomCreateTs = 14;</code>
   * @return The roomCreateTs.
   */
  @Override
  public long getRoomCreateTs() {
    return roomCreateTs_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (lts_ != 0L) {
      output.writeInt64(1, lts_);
    }
    if (vid_ != 0) {
      output.writeInt32(2, vid_);
    }
    if (!getVerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ver_);
    }
    if (!getScenarioBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scenario_);
    }
    if (errorCode_ != 0) {
      output.writeInt32(5, errorCode_);
    }
    if (!getUidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uid_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userName_);
    }
    if (streamUid_ != 0L) {
      output.writeInt64(8, streamUid_);
    }
    if (!getStreamSuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, streamSuid_);
    }
    if (!getRoleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, role_);
    }
    if (!getStreamSidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, streamSid_);
    }
    if (!getRtmSidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, rtmSid_);
    }
    if (!getRoomIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, roomId_);
    }
    if (roomCreateTs_ != 0L) {
      output.writeInt64(14, roomCreateTs_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(1, lts_);
    }
    if (vid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, vid_);
    }
    if (!getVerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ver_);
    }
    if (!getScenarioBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, scenario_);
    }
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(5, errorCode_);
    }
    if (!getUidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uid_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userName_);
    }
    if (streamUid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(8, streamUid_);
    }
    if (!getStreamSuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, streamSuid_);
    }
    if (!getRoleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, role_);
    }
    if (!getStreamSidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, streamSid_);
    }
    if (!getRtmSidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, rtmSid_);
    }
    if (!getRoomIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, roomId_);
    }
    if (roomCreateTs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(14, roomCreateTs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof ApaasUserJoin)) {
      return super.equals(obj);
    }
    ApaasUserJoin other = (ApaasUserJoin) obj;

    if (getLts()
            != other.getLts()) return false;
    if (getVid()
            != other.getVid()) return false;
    if (!getVer()
            .equals(other.getVer())) return false;
    if (!getScenario()
            .equals(other.getScenario())) return false;
    if (getErrorCode()
            != other.getErrorCode()) return false;
    if (!getUid()
            .equals(other.getUid())) return false;
    if (!getUserName()
            .equals(other.getUserName())) return false;
    if (getStreamUid()
            != other.getStreamUid()) return false;
    if (!getStreamSuid()
            .equals(other.getStreamSuid())) return false;
    if (!getRole()
            .equals(other.getRole())) return false;
    if (!getStreamSid()
            .equals(other.getStreamSid())) return false;
    if (!getRtmSid()
            .equals(other.getRtmSid())) return false;
    if (!getRoomId()
            .equals(other.getRoomId())) return false;
    if (getRoomCreateTs()
            != other.getRoomCreateTs()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLts());
    hash = (37 * hash) + VID_FIELD_NUMBER;
    hash = (53 * hash) + getVid();
    hash = (37 * hash) + VER_FIELD_NUMBER;
    hash = (53 * hash) + getVer().hashCode();
    hash = (37 * hash) + SCENARIO_FIELD_NUMBER;
    hash = (53 * hash) + getScenario().hashCode();
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + STREAMUID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStreamUid());
    hash = (37 * hash) + STREAMSUID_FIELD_NUMBER;
    hash = (53 * hash) + getStreamSuid().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + getRole().hashCode();
    hash = (37 * hash) + STREAMSID_FIELD_NUMBER;
    hash = (53 * hash) + getStreamSid().hashCode();
    hash = (37 * hash) + RTMSID_FIELD_NUMBER;
    hash = (53 * hash) + getRtmSid().hashCode();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId().hashCode();
    hash = (37 * hash) + ROOMCREATETS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRoomCreateTs());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ApaasUserJoin parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ApaasUserJoin parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ApaasUserJoin parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ApaasUserJoin parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static ApaasUserJoin parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ApaasUserJoin parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static ApaasUserJoin parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ApaasUserJoin parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static ApaasUserJoin parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ApaasUserJoin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * id = 9012
   * </pre>
   *
   * Protobuf type {@code google.protobuf.ApaasUserJoin}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:google.protobuf.ApaasUserJoin)
          ApaasUserJoinOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return APaasReportV2.internal_static_google_protobuf_ApaasUserJoin_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return APaasReportV2.internal_static_google_protobuf_ApaasUserJoin_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      ApaasUserJoin.class, Builder.class);
    }

    // Construct using io.agora.report.v2.protobuf.ApaasUserJoin.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      lts_ = 0L;

      vid_ = 0;

      ver_ = "";

      scenario_ = "";

      errorCode_ = 0;

      uid_ = "";

      userName_ = "";

      streamUid_ = 0L;

      streamSuid_ = "";

      role_ = "";

      streamSid_ = "";

      rtmSid_ = "";

      roomId_ = "";

      roomCreateTs_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return APaasReportV2.internal_static_google_protobuf_ApaasUserJoin_descriptor;
    }

    @Override
    public ApaasUserJoin getDefaultInstanceForType() {
      return ApaasUserJoin.getDefaultInstance();
    }

    @Override
    public ApaasUserJoin build() {
      ApaasUserJoin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ApaasUserJoin buildPartial() {
      ApaasUserJoin result = new ApaasUserJoin(this);
      result.lts_ = lts_;
      result.vid_ = vid_;
      result.ver_ = ver_;
      result.scenario_ = scenario_;
      result.errorCode_ = errorCode_;
      result.uid_ = uid_;
      result.userName_ = userName_;
      result.streamUid_ = streamUid_;
      result.streamSuid_ = streamSuid_;
      result.role_ = role_;
      result.streamSid_ = streamSid_;
      result.rtmSid_ = rtmSid_;
      result.roomId_ = roomId_;
      result.roomCreateTs_ = roomCreateTs_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ApaasUserJoin) {
        return mergeFrom((ApaasUserJoin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ApaasUserJoin other) {
      if (other == ApaasUserJoin.getDefaultInstance()) return this;
      if (other.getLts() != 0L) {
        setLts(other.getLts());
      }
      if (other.getVid() != 0) {
        setVid(other.getVid());
      }
      if (!other.getVer().isEmpty()) {
        ver_ = other.ver_;
        onChanged();
      }
      if (!other.getScenario().isEmpty()) {
        scenario_ = other.scenario_;
        onChanged();
      }
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (!other.getUid().isEmpty()) {
        uid_ = other.uid_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (other.getStreamUid() != 0L) {
        setStreamUid(other.getStreamUid());
      }
      if (!other.getStreamSuid().isEmpty()) {
        streamSuid_ = other.streamSuid_;
        onChanged();
      }
      if (!other.getRole().isEmpty()) {
        role_ = other.role_;
        onChanged();
      }
      if (!other.getStreamSid().isEmpty()) {
        streamSid_ = other.streamSid_;
        onChanged();
      }
      if (!other.getRtmSid().isEmpty()) {
        rtmSid_ = other.rtmSid_;
        onChanged();
      }
      if (!other.getRoomId().isEmpty()) {
        roomId_ = other.roomId_;
        onChanged();
      }
      if (other.getRoomCreateTs() != 0L) {
        setRoomCreateTs(other.getRoomCreateTs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      ApaasUserJoin parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ApaasUserJoin) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long lts_ ;
    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @return The lts.
     */
    @Override
    public long getLts() {
      return lts_;
    }
    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @param value The lts to set.
     * @return This builder for chaining.
     */
    public Builder setLts(long value) {

      lts_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳，必须存在
     * </pre>
     *
     * <code>int64 lts = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLts() {

      lts_ = 0L;
      onChanged();
      return this;
    }

    private int vid_ ;
    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @return The vid.
     */
    @Override
    public int getVid() {
      return vid_;
    }
    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @param value The vid to set.
     * @return This builder for chaining.
     */
    public Builder setVid(int value) {

      vid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * vid
     * </pre>
     *
     * <code>int32 vid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVid() {

      vid_ = 0;
      onChanged();
      return this;
    }

    private Object ver_ = "";
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return The ver.
     */
    public String getVer() {
      Object ref = ver_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ver_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return The bytes for ver.
     */
    public com.google.protobuf.ByteString
    getVerBytes() {
      Object ref = ver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        ver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @param value The ver to set.
     * @return This builder for chaining.
     */
    public Builder setVer(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      ver_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVer() {

      ver_ = getDefaultInstance().getVer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas版本号
     * </pre>
     *
     * <code>string ver = 3;</code>
     * @param value The bytes for ver to set.
     * @return This builder for chaining.
     */
    public Builder setVerBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      ver_ = value;
      onChanged();
      return this;
    }

    private Object scenario_ = "";
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return The scenario.
     */
    public String getScenario() {
      Object ref = scenario_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        scenario_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return The bytes for scenario.
     */
    public com.google.protobuf.ByteString
    getScenarioBytes() {
      Object ref = scenario_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        scenario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @param value The scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenario(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      scenario_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScenario() {

      scenario_ = getDefaultInstance().getScenario();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas场景，如education/meeting/entertainment
     * </pre>
     *
     * <code>string scenario = 4;</code>
     * @param value The bytes for scenario to set.
     * @return This builder for chaining.
     */
    public Builder setScenarioBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      scenario_ = value;
      onChanged();
      return this;
    }

    private int errorCode_ ;
    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @return The errorCode.
     */
    @Override
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {

      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 异常码，若有
     * </pre>
     *
     * <code>int32 errorCode = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {

      errorCode_ = 0;
      onChanged();
      return this;
    }

    private Object uid_ = "";
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return The uid.
     */
    public String getUid() {
      Object ref = uid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
    getUidBytes() {
      Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {

      uid_ = getDefaultInstance().getUid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas用户id，同RTM uid
     * </pre>
     *
     * <code>string uid = 6;</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      uid_ = value;
      onChanged();
      return this;
    }

    private Object userName_ = "";
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return The userName.
     */
    public String getUserName() {
      Object ref = userName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
    getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {

      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名，用于显示
     * </pre>
     *
     * <code>string userName = 7;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      userName_ = value;
      onChanged();
      return this;
    }

    private long streamUid_ ;
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @return The streamUid.
     */
    @Override
    public long getStreamUid() {
      return streamUid_;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @param value The streamUid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamUid(long value) {

      streamUid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>int64 streamUid = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamUid() {

      streamUid_ = 0L;
      onChanged();
      return this;
    }

    private Object streamSuid_ = "";
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return The streamSuid.
     */
    public String getStreamSuid() {
      Object ref = streamSuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        streamSuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return The bytes for streamSuid.
     */
    public com.google.protobuf.ByteString
    getStreamSuidBytes() {
      Object ref = streamSuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        streamSuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @param value The streamSuid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSuid(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      streamSuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamSuid() {

      streamSuid_ = getDefaultInstance().getStreamSuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtc流id
     * </pre>
     *
     * <code>string streamSuid = 9;</code>
     * @param value The bytes for streamSuid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSuidBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      streamSuid_ = value;
      onChanged();
      return this;
    }

    private Object role_ = "";
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return The role.
     */
    public String getRole() {
      Object ref = role_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        role_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return The bytes for role.
     */
    public com.google.protobuf.ByteString
    getRoleBytes() {
      Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {

      role_ = getDefaultInstance().getRole();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas角色
     * </pre>
     *
     * <code>string role = 10;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      role_ = value;
      onChanged();
      return this;
    }

    private Object streamSid_ = "";
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return The streamSid.
     */
    public String getStreamSid() {
      Object ref = streamSid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        streamSid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return The bytes for streamSid.
     */
    public com.google.protobuf.ByteString
    getStreamSidBytes() {
      Object ref = streamSid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        streamSid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @param value The streamSid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSid(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      streamSid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamSid() {

      streamSid_ = getDefaultInstance().getStreamSid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtc sid
     * </pre>
     *
     * <code>string streamSid = 11;</code>
     * @param value The bytes for streamSid to set.
     * @return This builder for chaining.
     */
    public Builder setStreamSidBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      streamSid_ = value;
      onChanged();
      return this;
    }

    private Object rtmSid_ = "";
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return The rtmSid.
     */
    public String getRtmSid() {
      Object ref = rtmSid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rtmSid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return The bytes for rtmSid.
     */
    public com.google.protobuf.ByteString
    getRtmSidBytes() {
      Object ref = rtmSid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        rtmSid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @param value The rtmSid to set.
     * @return This builder for chaining.
     */
    public Builder setRtmSid(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      rtmSid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRtmSid() {

      rtmSid_ = getDefaultInstance().getRtmSid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtm sid
     * </pre>
     *
     * <code>string rtmSid = 12;</code>
     * @param value The bytes for rtmSid to set.
     * @return This builder for chaining.
     */
    public Builder setRtmSidBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      rtmSid_ = value;
      onChanged();
      return this;
    }

    private Object roomId_ = "";
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return The roomId.
     */
    public String getRoomId() {
      Object ref = roomId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return The bytes for roomId.
     */
    public com.google.protobuf.ByteString
    getRoomIdBytes() {
      Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {

      roomId_ = getDefaultInstance().getRoomId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * apaas房间id，与rtc/rtm channelName相同
     * </pre>
     *
     * <code>string roomId = 13;</code>
     * @param value The bytes for roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomIdBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      roomId_ = value;
      onChanged();
      return this;
    }

    private long roomCreateTs_ ;
    /**
     * <pre>
     * room create timestamp
     * </pre>
     *
     * <code>int64 roomCreateTs = 14;</code>
     * @return The roomCreateTs.
     */
    @Override
    public long getRoomCreateTs() {
      return roomCreateTs_;
    }
    /**
     * <pre>
     * room create timestamp
     * </pre>
     *
     * <code>int64 roomCreateTs = 14;</code>
     * @param value The roomCreateTs to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCreateTs(long value) {

      roomCreateTs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * room create timestamp
     * </pre>
     *
     * <code>int64 roomCreateTs = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomCreateTs() {

      roomCreateTs_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.ApaasUserJoin)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.ApaasUserJoin)
  private static final ApaasUserJoin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ApaasUserJoin();
  }

  public static ApaasUserJoin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApaasUserJoin>
          PARSER = new com.google.protobuf.AbstractParser<ApaasUserJoin>() {
    @Override
    public ApaasUserJoin parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApaasUserJoin(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApaasUserJoin> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ApaasUserJoin> getParserForType() {
    return PARSER;
  }

  @Override
  public ApaasUserJoin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

