// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/users.proto

package io.agora.edu.core.internal.report.v2.protobuf;

public final class APaasReportV2 {
  private APaasReportV2() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_google_protobuf_ApaasUserJoin_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_google_protobuf_ApaasUserJoin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_google_protobuf_ApaasUserQuit_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_google_protobuf_ApaasUserQuit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_google_protobuf_ApaasUserReconnect_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_google_protobuf_ApaasUserReconnect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\017src/users.proto\022\017google.protobuf\"\367\001\n\rA" +
                    "paasUserJoin\022\013\n\003lts\030\001 \001(\003\022\013\n\003vid\030\002 \001(\005\022\013" +
                    "\n\003ver\030\003 \001(\t\022\020\n\010scenario\030\004 \001(\t\022\021\n\terrorCo" +
                    "de\030\005 \001(\005\022\013\n\003uid\030\006 \001(\t\022\020\n\010userName\030\007 \001(\t\022" +
                    "\021\n\tstreamUid\030\010 \001(\003\022\022\n\nstreamSuid\030\t \001(\t\022\014" +
                    "\n\004role\030\n \001(\t\022\021\n\tstreamSid\030\013 \001(\t\022\016\n\006rtmSi" +
                    "d\030\014 \001(\t\022\016\n\006roomId\030\r \001(\t\022\023\n\013roomCreatTs\030\016" +
                    " \001(\003\"\342\001\n\rApaasUserQuit\022\013\n\003lts\030\001 \001(\003\022\013\n\003v" +
                    "id\030\002 \001(\005\022\013\n\003ver\030\003 \001(\t\022\020\n\010scenario\030\004 \001(\t\022" +
                    "\021\n\terrorCode\030\005 \001(\005\022\013\n\003uid\030\006 \001(\t\022\020\n\010userN" +
                    "ame\030\007 \001(\t\022\021\n\tstreamUid\030\010 \001(\003\022\022\n\nstreamSu" +
                    "id\030\t \001(\t\022\014\n\004role\030\n \001(\t\022\021\n\tstreamSid\030\013 \001(" +
                    "\t\022\016\n\006rtmSid\030\014 \001(\t\022\016\n\006roomId\030\r \001(\t\"\347\001\n\022Ap" +
                    "aasUserReconnect\022\013\n\003lts\030\001 \001(\003\022\013\n\003vid\030\002 \001" +
                    "(\005\022\013\n\003ver\030\003 \001(\t\022\020\n\010scenario\030\004 \001(\t\022\021\n\terr" +
                    "orCode\030\005 \001(\005\022\013\n\003uid\030\006 \001(\t\022\020\n\010userName\030\007 " +
                    "\001(\t\022\021\n\tstreamUid\030\010 \001(\003\022\022\n\nstreamSuid\030\t \001" +
                    "(\t\022\014\n\004role\030\n \001(\t\022\021\n\tstreamSid\030\013 \001(\t\022\016\n\006r" +
                    "tmSid\030\014 \001(\t\022\016\n\006roomId\030\r \001(\tB\210\001\n\033io.agora" +
                    ".report.v2.protobufB\rAPaasReportV2P\001Z.go" +
                    "ogle.golang.org/protobuf/types/known/emp" +
                    "typb\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.WellKnow" +
                    "nTypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_google_protobuf_ApaasUserJoin_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_ApaasUserJoin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_protobuf_ApaasUserJoin_descriptor,
            new String[] { "Lts", "Vid", "Ver", "Scenario", "ErrorCode", "Uid", "UserName", "StreamUid", "StreamSuid", "Role", "StreamSid", "RtmSid", "RoomId", "RoomCreatTs", });
    internal_static_google_protobuf_ApaasUserQuit_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_ApaasUserQuit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_protobuf_ApaasUserQuit_descriptor,
            new String[] { "Lts", "Vid", "Ver", "Scenario", "ErrorCode", "Uid", "UserName", "StreamUid", "StreamSuid", "Role", "StreamSid", "RtmSid", "RoomId", });
    internal_static_google_protobuf_ApaasUserReconnect_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_ApaasUserReconnect_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_protobuf_ApaasUserReconnect_descriptor,
            new String[] { "Lts", "Vid", "Ver", "Scenario", "ErrorCode", "Uid", "UserName", "StreamUid", "StreamSuid", "Role", "StreamSid", "RtmSid", "RoomId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}